{{- if .Values.stack.hook.enabled }}
{{- if .Values.stack.hook.downloadEnabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: download-hook
  namespace: {{ .Release.Namespace }}
data:
  entrypoint.sh: |-
    #!/usr/bin/env bash
    # This script is designed to download the Hook artifacts.
    set -euxo pipefail
    cd /output
    rm -f *.tar.gz checksum.txt vmlinuz* initramfs*
    base_loc="{{ .Values.stack.hook.downloadURL }}"
    files="$base_loc/hook_aarch64.tar.gz $base_loc/hook_x86_64.tar.gz $base_loc/checksum.txt"
    tmp_dir=$(mktemp -d)
    for f in ${files}; do
      echo "${f}"
      wget -P "${tmp_dir}" "${f}"
    done
    # releases of HookOS > 0.8.1 provide more binaries.
    # We only need the hook_aarch64 and hook_x86_64 binaries so we filter out the rest.
    (cd "${tmp_dir}" && sed -i '/hook_x86_64\|hook_aarch64/!d' checksum.txt && sha512sum -c checksum.txt)
    mv "${tmp_dir}"/checksum.txt .
    for f in ${tmp_dir}/*.tar.gz; do tar --no-same-permissions --overwrite -ozxvf "${f}" && rm -f "${f}"; done
    rm -rf "${tmp_dir}"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: download-hook
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 50
  template:
    metadata:
      labels:
        app: download-hook
    spec:
      containers:
        - name: download-hook
          image: {{ .Values.stack.hook.image }}
          command: [ "/script/entrypoint.sh" ]
          volumeMounts:
            - mountPath: /output
              name: hook-artifacts
            - mountPath: /script
              name: configmap-volume
      restartPolicy: OnFailure
      volumes:
        - name: hook-artifacts
          hostPath:
            path: {{ .Values.stack.hook.downloadsDest }}
            type: DirectoryOrCreate
        - name: configmap-volume
          configMap:
            defaultMode: 0700
            name: download-hook
{{- end }}
{{- end }}