{{- if .Values.stack.enabled }}
{{- $sourceInterface := .Values.stack.relay.sourceInterface -}}
{{- $ifaceModes := dict "ipvlan" "" "macvlan" "" -}}
{{- $dhcpInterfaceType := .Values.stack.relay.interfaceMode -}}
{{- if not (hasKey $ifaceModes $dhcpInterfaceType) -}}
  {{- fail "invalid value at .stack.relay.interfaceMode: valid modes include ipvlan and macvlan" -}}
{{- end -}}
{{- $dhcpInterfaceName := printf "%s0" $dhcpInterfaceType -}}
{{- $listenBroadcast := true -}}
{{- if not (quote .Values.stack.relay.listenBroadcastTraffic | empty) -}}
  {{- $listenBroadcast = .Values.stack.relay.listenBroadcastTraffic -}}
{{- end -}}
{{- if not $listenBroadcast -}}
  {{- $dhcpInterfaceName = "eth0" -}}
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.stack.name}}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      {{- with .Values.stack.selector }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
      labels:
        {{- with .Values.stack.selector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if not .Values.stack.service.enabled }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      hostPID: true
      containers:
      - name: {{ .Values.stack.name }}
        image: {{ .Values.stack.image }}
        command: ["/bin/bash", "-xeuc"]
        args:
        - |
          POD_NAMESERVER=$(awk '/nameserver/ {print $2}' /etc/resolv.conf) \
            envsubst '$POD_NAMESERVER' \
            </tmp/nginx.conf.template \
            >/etc/nginx/nginx.conf
          exec nginx -g 'daemon off;'
        ports:
        - containerPort: {{ .Values.hegel.deployment.port }}
          protocol: TCP
          name: {{ .Values.hegel.deployment.portName }}
        - containerPort: {{ .Values.tink.server.deployment.port }}
          protocol: TCP
          name: {{ .Values.tink.server.deployment.portName }}
        - containerPort: {{ .Values.stack.hook.port }}
          protocol: TCP
          name: hook-http
        {{- if not .Values.smee.hostNetwork }}
        - containerPort: {{ .Values.smee.http.port }}
          protocol: TCP
          name: {{ .Values.smee.http.name }}
        - containerPort: {{ .Values.smee.tftp.port }}
          protocol: UDP
          name: {{ .Values.smee.tftp.name }}
        - containerPort: {{ .Values.smee.syslog.port }}
          protocol: UDP
          name: {{ .Values.smee.syslog.name }}
        {{- end }}
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /tmp
          readOnly: true
          name: nginx-conf
        {{- if .Values.stack.hook.enabled }}
        - mountPath: /usr/share/nginx/html
          name: hook-artifacts
        {{- end }}
      {{- if .Values.stack.relay.enabled }}
      - name: {{ .Values.stack.relay.name }}
        image: {{ .Values.stack.relay.image }}
        args: ["-m", "{{ .Values.stack.relay.presentGiaddrAction }}", "-c", "{{ .Values.stack.relay.maxHopCount }}", "-id", "{{ $dhcpInterfaceName }}", "-iu", "eth0", "-U", "eth0", "smee.{{ .Release.Namespace }}.svc.{{ .Values.stack.clusterDomain }}."]
        ports:
        - containerPort: 67
          protocol: UDP
          name: dhcp
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          capabilities:
            add:
              - NET_RAW
      {{- end }}
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf.template
      {{- if .Values.stack.hook.enabled }}
      - name: hook-artifacts
        hostPath:
          path: {{ .Values.stack.hook.downloadsDest }}
          type: DirectoryOrCreate
      {{- end }}
      {{- if and .Values.stack.relay.enabled $listenBroadcast }}
      initContainers:
      - name: relay-broadcast-interface
        command:
          - /bin/sh
          - -c
          - |
            # This script allows us to listen and respond to DHCP requests on a host network interface and interact with Smee properly.
            # This is used instead of `hostNetwork: true` because the dhcp relay requires clear paths for listening for broadcast traffic
            # and sending/receiving unicast traffic to/from Smee.
            set -xe
            # if sourceInterface is not set use the interface from the default route
            srcInterface="{{ $sourceInterface }}"
            if [ -z "$srcInterface" ]; then
              srcInterface=$(nsenter -t1 -n ip route | awk '/default/ {print $5}' | head -n1)
            fi
            # Create the interface. TODO: If this fails, try again with a different name?
            {{- if eq $dhcpInterfaceType "ipvlan" }}
            nsenter -t1 -n ip link add {{ $dhcpInterfaceName }} link ${srcInterface} type ipvlan mode l2
            {{- else }}
            nsenter -t1 -n ip link add {{ $dhcpInterfaceName }} link ${srcInterface} type macvlan mode bridge
            {{- end }}
            # Move the interface into the POD.
            pid=$(echo $$)
            nsenter -t1 -n ip link set {{ $dhcpInterfaceName }} netns ${pid} || nsenter -t1 -n ip link delete {{ $dhcpInterfaceName }}
            # Set the interface up
            ip link set {{ $dhcpInterfaceName }} up
            # Set the IP address
            ip addr add 127.1.1.1/32 dev {{ $dhcpInterfaceName }} noprefixroute || true
            {{- if eq $dhcpInterfaceType "ipvlan" }}
            # There is an issue with ipvlan interfaces. They do not start receiving broadcast packets after creation.
            # This is a workaround to get broadcast packets flowing.
            # TODO(jacobweinstock): Investigate this deeper and see if this is a kernel bug.
            nsenter -t1 -n ip link del {{ $dhcpInterfaceName }}-wa || true
            nsenter -t1 -n nmap --script broadcast-dhcp-discover
            nsenter -t1 -n ip link add {{ $dhcpInterfaceName }}-wa link ${srcInterface} type ipvlan mode l2 bridge || true
            {{- end }}
        image: {{ .Values.stack.relay.initImage }}
        securityContext:
          privileged: true
      {{- end }}
      {{- if .Values.stack.singleNodeClusterConfig.controlPlaneTolerationsEnabled }}
      tolerations:
      {{- include "singleNodeClusterConfig" . | indent 6 }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          {{- include "preferWorkerNodes" (dict "nodeAffinityWeight" .Values.stack.singleNodeClusterConfig.nodeAffinityWeight) | indent 10 }}
      {{- end }}
{{- if .Values.stack.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.stack.name }}
  name: {{ .Values.stack.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.stack.service.type }}
  {{- if eq .Values.stack.service.type "LoadBalancer" }}
  {{- if .Values.stack.lbClass }}
  loadBalancerClass: {{ .Values.stack.lbClass }}
  {{- end }}
  loadBalancerIP: {{ .Values.stack.loadBalancerIP }}
  externalTrafficPolicy: Local
  {{- end }}
  ports:
  - name: {{ .Values.hegel.name }}
    port: {{ .Values.hegel.deployment.port }}
    protocol: TCP
  - name: {{ .Values.tink.server.name }}
    port: {{ .Values.tink.server.deployment.port }}
    protocol: TCP
  - name: {{ .Values.stack.hook.name }}
    port: {{ .Values.stack.hook.port }}
    protocol: TCP
  - port: {{ .Values.smee.http.port }}
    protocol: TCP
    name: {{ .Values.smee.http.name }}
  - port: {{ .Values.smee.tftp.port }}
    protocol: UDP
    name: {{ .Values.smee.tftp.name }}
  - port: {{ .Values.smee.syslog.port }}
    protocol: UDP
    name: {{ .Values.smee.syslog.name }}
  - port: 67
    protocol: UDP
    name: dhcp
  selector:
    {{- with .Values.stack.selector }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
